# Generated by Django 2.0.1 on 2018-01-22 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-Mail Adresse')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Nachname')),
                ('active', models.BooleanField(default=True, verbose_name='Ist Aktiviert?')),
                ('staff', models.BooleanField(default=False, verbose_name='Ist Administrator?')),
                ('admin', models.BooleanField(default=False, verbose_name='Ist Super-Administrator')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Nutzer',
                'verbose_name_plural': 'Benutzer',
            },
        ),
    ]
